### PR TITLE
add and configure parcel with env and scss support

### PR DESCRIPTION
**Pull request by elshanx**
I saw your [post](https://www.facebook.com/groups/azeri.developers/posts/4458360260880795/) and had free time to help. 

I didn't add .env file to the gitignore, you are going to have to do that on your own😅

let me know if you need any further help.
Enjoy!

### CODE REVIEW

**Comment by ISnowFoxI** [comment]
@elshanx  Thank you for your help.
so umm, there is one tiny problem though. Everything is working locally, but when I try to build it on Netlify, it breaks. I did add the build command "npm run build" in the deploy settings. It shows that the build is completed successfully but the site appears to be broken.

**Comment by elshanx** [comment]
@ISnowFoxI well you need to do the following things: 

- publish directory should be dist 


image

- and you still need to add the env variables to netlify

image

if these doesn't help, you can try to add parcel-bundler as a dependency instead of dev-dependency

**Comment by ISnowFoxI** [comment]
@elshanx Oh I see, I haven't added dist to the Publish directory. All seems to be working correctly now. Thank you for everything. Learned a lot

**Comment by elshanx** [comment]
@ISnowFoxI btw I see that you're still compiling css to scss. you don't need to anymore because parcel takes care of that for you.

**Comment by ISnowFoxI** [comment]
@elshanx alright, I'll fix that soon, I still have to make it look better for the desktop version. Got to learn more about Parcel xD

**Pull request merged**
